### ISSUE TITLE
User deactivated

### ISSUE THREAD

**Issue by DAThosting** [easy-wi/whmcs#15]
If user have more than one product and one of this product terminate, the whole user account is set to deactivated.
The user can't login anymore since I set him to activate, because a product is still running for him.

**Comment by ulrichblock** [comment]
As so many times before, you seem to be the only one that is affected. So again, I cannot do a thing without the excact configuration and so on.

**Comment by DAThosting** [comment]
Hier wäre ein Log dazu:
https://pastebin.com/qFCtUKH2

Dieser Kunde hat ein weiteres Produkt in Easy-Wi, jedoch wird der Kunde deaktiviert, somit kann er nicht mehr auf seinen Account zugreifen.

Hier noch meine EW-WHMCS-Modul Einstellungen:
http://prntscr.com/fnwxpi

EW: 6.0.0
WHMCS: 6.3.1
PHP: 5.6.30-0+deb8u1

**Comment by danir-de** [comment]
Having the same problem right here and it's easy to reproduce.

User had several voice servers activated, then a game server creation was requested.

With the creation of the game server in whmcs, #40 was triggered because there was no available root server. The complete user got suspended and all servers of the users were shut down.

We had to activate the user manually to make everything work again. Upon modul command retry, the whole user gets deactivated again, when there is no available game root.
